In [1]:
import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

### Credits
Author: Denny Britz
https://github.com/dennybritz/reinforcement-learning

In [2]:
pp = pprint.PrettyPrinter(indent=2)
env = GridworldEnv()

In [3]:
env.render()

T  o  o  o
o  o  o  o
o  o  o  o
o  o  x  T


In [11]:
env.P[15][3]
# returns (prob, next_state, reward, done)

[(1.0, 15, 0.0, True)]

In [7]:
env.nS

16

In [8]:
env.nA

4

![Value iteration](./images/value_iteration.png)

In [30]:
def value_iteration(env, theta=0.0001, discount_factor=1.0):
    """
    Value Iteration Algorithm.
    
    Args:
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
        
    Returns:
        A tuple (policy, V) of the optimal policy and the optimal value function.  
    """
    def one_step_lookahead(state, V):
        """
        Helper function to calculate the value for all action in a given state.
        We have to compute the expected value for each action
        
        Args:
            state: The state to consider (int)
            V: The value to use as an estimator, Vector of length env.nS
        
        Returns:
            A vector of length env.nA containing the expected value of each action.
        """
        A = np.zeros(env.nA)
        for a in range(env.nA):
            for prob, next_state, reward, done in env.P[state][a]:
                A[a] += prob * (reward + discount_factor * V[next_state])
        return A
    
    def get_best_action_value(state,V):
        """
        Helper function to get the best action for a given state
        
        Args:
            state: The state to consider (int)
            V: The value to use as an estimator, Vector of length env.nS
        
        Returns:
            a: best action (integer)
        
        """
        expected_state_values = one_step_lookahead(s,V)
        best_state_value = np.max(expected_state_values)
        best_action = np.random.choice(np.where(expected_state_values == best_state_value)[0])
        return best_action,best_state_value
    

    V = np.zeros(env.nS)
    while True:
        delta = 0.0
        for s in range(env.nS):
            current_state_value = V[s]
            
            # plug in the update for V(s) from the algorithm given above
            # Tip: you can use the get_best_action_value method
            pass
            
            delta = max(delta,abs(best_state_value-current_state_value))
        print(V,delta)
        if delta < theta:
            break
            
    policy = np.zeros([env.nS, env.nA])
    for s in range(env.nS):
        # update the policy distribution
        # Tip: you can use the get_best_action_value method
        pass
    
    # That was Easy!
    return policy, V

In [31]:
policy, v = value_iteration(env)

print("Policy Probability Distribution:")
print(policy)
print("")

print("Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(policy, axis=1), env.shape))
print("")

print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

[ 0. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  0.] 1.0
[ 0. -1. -2. -2. -1. -2. -2. -2. -2. -2. -2. -1. -2. -2. -1.  0.] 1.0
[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.] 1.0
[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.] 0.0
Policy Probability Distribution:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]

Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):
[[0 3 3 2]
 [0 3 1 2]
 [0 3 2 2]
 [0 1 1 1]]

Value Function:
[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.]

Reshaped Grid Value Function:
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]



In [28]:
# Test the value function
expected_v = np.array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)